#!/bin/bash
# Tlotliso Mapana

for j in {1..211}
do
	head -n $j data/AllDams.txt > TempData.txt
	name=$(cat TempData.txt |cut -d$'\n' -f $j|cut -d',' -f1)
	java -cp ./bin DamAVLApp "$name" >> data/AVL/TestResults2.txt
	java -cp ./bin DamBSTApp "$name" >> data/BST/TestResults2.txt
done
echo "------------------------------------------------------------" >> data/AVL/TestResults2.txt
echo "------------------------------------------------------------" >> data/BST/TestResults2.txt
#done
